create table if not exists public.user_devices (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  device_id text not null,
  user_agent text,
  ip text,
  city text,
  region text,
  country text,
  last_login_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists user_devices_user_device_unique
  on public.user_devices (user_id, device_id);

create index if not exists user_devices_user_last_login_idx
  on public.user_devices (user_id, last_login_at desc);

alter table public.user_devices enable row level security;

drop policy if exists "user_devices_select_own" on public.user_devices;
create policy "user_devices_select_own"
  on public.user_devices
  for select
  using (auth.uid() = user_id);

drop policy if exists "user_devices_insert_own" on public.user_devices;
create policy "user_devices_insert_own"
  on public.user_devices
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "user_devices_update_own" on public.user_devices;
create policy "user_devices_update_own"
  on public.user_devices
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
